---
title: "R coding Exercise"
output: 
  html_document:
    toc: FALSE
---

```{r packages, echo=FALSE}
# Load Package dslabs
# load dslabs for dataset
library("dslabs")
# load tidyverse to tidy and plot data
library("tidyverse")
```

```{r view_gapminder, eval=FALSE, echo=FALSE}
gapminder

# View gampminder help section
help(gapminder)

# view data structure
str(gapminder)

# view data summary     
summary(gapminder)

# view type of object
class("gapminder")
```

```{r africadata}
# Create object named africa data. Filter gapminder to create new dataset with only African countries.
africadata <- gapminder %>% filter(continent == "Africa")

# view data summary for africadata
summary(africadata)

#view structure for africadata
str(africadata)
```

```{r infant_mortality_life_expectancy}
# for observations in africadata, create object with infant_mortality and life_expectancy, only
imle <- data.frame(africadata$infant_mortality, africadata$life_expectancy)
imle <- imle %>% rename(infant_mortality = africadata.infant_mortality,
                life_expectancy = africadata.life_expectancy)

#view summary
summary(imle)

#view structure
str(imle)
```

```{r population_life_expectancy}
# for observations in africadata, create object with population and life_expectancy, only
ple <- data.frame(africadata$population, africadata$life_expectancy)
ple <- ple %>% rename(population = africadata.population,
                      life_expectancy = africadata.life_expectancy)

#view summary
summary(ple)

#view structure
str(ple)
```

```{r imle_plot}
# plot life expectancy as a function of infant mortality and as a function of population size

imle_plot <- imle %>% 
             ggplot(aes(x=infant_mortality, y=life_expectancy))+
             geom_point()
         
imle_plot         
```

```{r ple_plot}
ple_plot <- ple %>% 
            ggplot(aes(x=log10(population), y=life_expectancy))+
            geom_point()

ple_plot
```

```{r na_imle}
# ple_plot graph seems to show that as population growth has a positive correlation with life expectancy. Each individual streak represents a different country

# Which years have the highest number of NAs for infant mortality?
na_imle <- africadata %>% 
           select(year,infant_mortality) %>% 
           filter(is.na(infant_mortality)) %>% 
           count(year) %>% 
           arrange(-n)

rmarkdown::paged_table(na_imle)           
           
```

```{r africadata2k}
# Create a new object by extracting only the data for the year 2000 from the africadata object
africadata2k <- africadata %>% filter(year == 2000)

# View Summary
summary(africadata2k)

# View Structure
str(africadata2k)
```

```{r imle_plot2k}
# Plot africadata for year 2000, x is infant mortality, y is life expectancy
imle_plot2k <- africadata2k %>% 
               select(year,infant_mortality,life_expectancy) %>%
               ggplot(aes(x=infant_mortality, y=life_expectancy))+
               geom_point()
         
imle_plot2k         
```


```{r ple_plot2k}
# Plot africa data for year 2000, x is population, y is life expectancy
ple_plot2k <- africadata2k %>%
              select(year,population,life_expectancy) %>%
              ggplot(aes(x=log10(population),y=life_expectancy))+
              geom_point()

ple_plot2k
```

```{r fit1}
# Line of best fit with infant mortality
fit1 <- africadata2k %>% 
  select(year,infant_mortality,life_expectancy) %>%
  ggplot(aes(x=infant_mortality, y=life_expectancy))+
  geom_point()+
  geom_smooth(method="lm")

# Run plot
fit1             
```

```{r fit2}
# Line of best fit with population
fit2 <- africadata2k %>%
  select(year,population,life_expectancy) %>%
  ggplot(aes(x=log10(population),y=life_expectancy))+
  geom_point()+
  geom_smooth(method="lm")

fit2
```


